//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace galari.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class otogalariEntities : DbContext
    {
        public otogalariEntities()
            : base("name=otogalariEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<müsteri> müsteri { get; set; }
        public DbSet<otomobil> otomobil { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
