//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace galari.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class müsteri
    {
        public müsteri()
        {
            this.otomobil = new HashSet<otomobil>();
        }
    
        public int müsteriID { get; set; }
        public string mAdi { get; set; }
        public string mSoyadi { get; set; }
        public int mOtoID { get; set; }
        public string mOtoadi { get; set; }
    
        public virtual ICollection<otomobil> otomobil { get; set; }
    }
}
